name: CI/CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  FA_TOKEN: ${{ secrets.FA_TOKEN }}
  ANDROID_RELEASE_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
  ANDROID_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}
  NDK_VERSION: 29.0.14206865
  JAVA_VERSION: 21

jobs:
  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-js
      - run: pnpm audit --prod

  check:
    name: Check
    needs: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-js
      - run: pnpm run check

  build:
    name: Build
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-js
      - uses: ./.github/actions/build

      - uses: actions/upload-artifact@v4
        with:
          name: android-app-apk
          if-no-files-found: error
          path: src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk

      - uses: actions/upload-artifact@v4
        with:
          name: android-app-bundle
          if-no-files-found: error
          path: src-tauri/gen/android/app/build/outputs/bundle/universalRelease/app-universal-release.aab
