name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type (major, minor, patch)"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch
      release_notes:
        description: "Release notes"
        required: true
        type: string

env:
  FA_TOKEN: ${{ secrets.FA_TOKEN }}
  ANDROID_RELEASE_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
  ANDROID_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}
  NDK_VERSION: 29.0.14206865
  JAVA_VERSION: 21

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-js
      - uses: ./.github/actions/build

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version in package.json
        run: |
          set -e  # exit immediately if any command fails
          TAGGED_VERSION=$(npm version ${{ inputs.release_type }})
          echo "TAGGED_VERSION=$TAGGED_VERSION" >> $GITHUB_ENV

      - name: Push commit
        run: git push origin HEAD:main --follow-tags

      - name: Rename APK and AAB
        run: |
          cp src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk src-tauri/gen/android/app/build/outputs/apk/universal/release/hungry-noodle-${{ env.TAGGED_VERSION }}.apk
          cp src-tauri/gen/android/app/build/outputs/bundle/universalRelease/app-universal-release.aab src-tauri/gen/android/app/build/outputs/bundle/universalRelease/hungry-noodle-${{ env.TAGGED_VERSION }}.aab

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: "Hungry Noodle ${{ env.TAGGED_VERSION }}"
          tag_name: ${{ env.TAGGED_VERSION }}
          body: ${{ inputs.release_notes }}
          files: |
            src-tauri/gen/android/app/build/outputs/apk/universal/release/hungry-noodle-${{ env.TAGGED_VERSION }}.apk
            src-tauri/gen/android/app/build/outputs/bundle/universalRelease/hungry-noodle-${{ env.TAGGED_VERSION }}.aab
