name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type (major, minor, patch)"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch
      release_notes:
        description: "Release notes"
        required: true
        type: string

env:
  FA_TOKEN: ${{ secrets.FA_TOKEN }}
  ANDROID_RELEASE_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
  ANDROID_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}
  NDK_VERSION: 29.0.14206865
  JAVA_VERSION: 21

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - run: pnpm install --frozen-lockfile

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;${{ env.NDK_VERSION }}"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: Extract android signing key from env
        run: |
          echo "${{ env.ANDROID_RELEASE_KEYSTORE }}" > src-tauri/gen/android/upload-keystore.jks.base64
          base64 -d src-tauri/gen/android/upload-keystore.jks.base64 > src-tauri/gen/android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "keyAlias=upload" > src-tauri/gen/android/key.properties
          echo "password=${{ env.ANDROID_RELEASE_KEYSTORE_PASSWORD }}" >> src-tauri/gen/android/key.properties
          echo "storeFile=upload-keystore.jks" >> src-tauri/gen/android/key.properties

      - run: pnpm run build:android:prod
        env:
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/${{ env.NDK_VERSION }}

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version in package.json
        run: |
          echo "TAGGED_VERSION=$(npm version ${{ inputs.release_type }})" >> $GITHUB_ENV

      - name: Push commit
        run: git push origin HEAD:main --follow-tags

      - name: Rename APK and AAB
        run: |
          cp src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk src-tauri/gen/android/app/build/outputs/apk/universal/release/hungry-noodle-${{ env.TAGGED_VERSION }}.apk
          cp src-tauri/gen/android/app/build/outputs/bundle/universalRelease/app-universal-release.aab src-tauri/gen/android/app/build/outputs/bundle/universalRelease/hungry-noodle-${{ env.TAGGED_VERSION }}.aab

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: "Hungry Noodle ${{ env.TAGGED_VERSION }}"
          tag_name: ${{ env.TAGGED_VERSION }}
          body: ${{ inputs.release_notes }}
          files: |
            src-tauri/gen/android/app/build/outputs/apk/universal/release/hungry-noodle-${{ env.TAGGED_VERSION }}.apk
            src-tauri/gen/android/app/build/outputs/bundle/universalRelease/hungry-noodle-${{ env.TAGGED_VERSION }}.aab
