name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type (major, minor, patch)"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch
      release_notes:
        description: "Release notes"
        required: true
        type: string

env:
  FA_TOKEN: ${{ secrets.FA_TOKEN }}
  ANDROID_RELEASE_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
  ANDROID_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}
  NDK_VERSION: 29.0.14206865
  JAVA_VERSION: 21

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-js
      - uses: ./.github/actions/build

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.HNR_GH_APP_ID }}
          private-key: ${{ secrets.HNR_GH_APP_PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Configure git user & remote
        env:
          APP_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${APP_TOKEN}@github.com/${{ github.repository }}

      - name: Bump version in package.json
        run: |
          set -e  # exit immediately if any command fails
          TAGGED_VERSION=$(npm version ${{ inputs.release_type }})
          echo "TAGGED_VERSION=$TAGGED_VERSION" >> $GITHUB_ENV

      - name: Push commit
        run: git push origin HEAD:main --follow-tags

      - name: Rename APK and AAB
        run: |
          cp src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk src-tauri/gen/android/app/build/outputs/apk/universal/release/hungry-noodle-${{ env.TAGGED_VERSION }}.apk
          cp src-tauri/gen/android/app/build/outputs/bundle/universalRelease/app-universal-release.aab src-tauri/gen/android/app/build/outputs/bundle/universalRelease/hungry-noodle-${{ env.TAGGED_VERSION }}.aab

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: "Hungry Noodle ${{ env.TAGGED_VERSION }}"
          tag_name: ${{ env.TAGGED_VERSION }}
          body: ${{ inputs.release_notes }}
          files: |
            src-tauri/gen/android/app/build/outputs/apk/universal/release/hungry-noodle-${{ env.TAGGED_VERSION }}.apk
            src-tauri/gen/android/app/build/outputs/bundle/universalRelease/hungry-noodle-${{ env.TAGGED_VERSION }}.aab
